packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "@prisma/engines": true
  esbuild: true
  prisma: true
  sharp: set this to true or false
  unrs-resolver: set this to true or false
  workerd: set this to true or false

onlyBuiltDependencies:
  - "@prisma/engines"
  - esbuild
  - prisma
  - sharp
  - unrs-resolver
  - workerd
