const photoPolicy = (
  mode: "AI" | "RECORD",
  extra: Record<string, unknown> = {},
) => ({
  type: "PHOTO",
  requiredPhotoCount: 1,
  photoVerificationMode: mode,
  ...(mode === "AI" ? { fallbackToAdminReview: true } : {}),
  ...extra,
});

const quizPolicy = (
  answer: string,
  choices?: readonly string[],
  explanation?: string,
) => ({
  type: "QUIZ",
  answer,
  ...(choices ? { choices: [...choices] } : {}),
  ...(explanation ? { explanation } : {}),
});

export const anseongMissionSeed = [
  {
    order: 1,
    title: "반짝이는 안성",
    description: "안성의 전통 공예인 유기와 관련된 물건이나 상징을 찾아보세요.",
    category: "탐색",
    difficulty: 1,
    similarityGroup: "ANSEONG_CRAFT",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("AI", { requiredSubject: "안성 유기와 관련된 물건 또는 상징" }),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 2,
    title: "맞춤의 탄생",
    description: "Quiz! '안성맞춤'이라는 표현과 깊은 관련이 있는 안성의 전통 공예품은 무엇일까요?",
    category: "퀴즈",
    difficulty: 1,
    similarityGroup: "ANSEONG_CRAFT",
    status: "ACTIVE",
    kind: "QUIZ",
    verificationPolicy: quizPolicy("유기", ["①도자기", "②유기", "③한지", "④목기"], "정답! 안성은 유기로 유명한 지역이에요. 주문에 꼭 맞게 만든 물건에서 '안성맞춤'이라는 표현이 전해졌답니다."),
    targetValue: null,
    targetUnit: null,
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 3,
    title: "여기, 안성 어때?",
    description: "관광안내서에는 없을 것 같은 나만의 포토스팟을 발견해보세요.",
    category: "관찰·수집",
    difficulty: 2,
    similarityGroup: "ANSEONG_SCENERY",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("RECORD"),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 4,
    title: "청록의 시인",
    description: "Quiz! 안성 출신으로 『해』, 『청산도』 등의 작품을 남긴 시인은 누구일까요?",
    category: "퀴즈",
    difficulty: 3,
    similarityGroup: "ANSEONG_POET",
    status: "ACTIVE",
    kind: "QUIZ",
    verificationPolicy: quizPolicy("박두진"),
    targetValue: null,
    targetUnit: null,
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 5,
    title: "아슬아슬 줄타기",
    description: "Quiz! 남사당놀이에서 아슬아슬한 줄타기를 무엇이라고 부를까요?",
    category: "퀴즈",
    difficulty: 2,
    similarityGroup: "ANSEONG_NAMSADANG",
    status: "ACTIVE",
    kind: "QUIZ",
    verificationPolicy: quizPolicy("어름", ["①어름", "②버나", "③풍물놀이", "④살판"]),
    targetValue: null,
    targetUnit: null,
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 6,
    title: "빙글빙글 한판",
    description: "Quiz! 남사당놀이에서 접시 같은 물체를 돌리는 놀이의 이름은 무엇일까요?",
    category: "퀴즈",
    difficulty: 2,
    similarityGroup: "ANSEONG_NAMSADANG",
    status: "ACTIVE",
    kind: "QUIZ",
    verificationPolicy: quizPolicy("버나", ["①덜미", "②덧뵈기", "③살판", "④버나"]),
    targetValue: null,
    targetUnit: null,
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 7,
    title: "열다섯의 꼭두쇠",
    description: "Quiz! 열다섯의 어린 나이에 남사당패의 꼭두쇠가 된 안성의 인물은 누구인가요?",
    category: "퀴즈",
    difficulty: 3,
    similarityGroup: "ANSEONG_NAMSADANG",
    status: "ACTIVE",
    kind: "QUIZ",
    verificationPolicy: quizPolicy("바우덕이"),
    targetValue: null,
    targetUnit: null,
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 8,
    title: "윤슬을 따라서",
    description: "금광호수의 물길을 따라 천천히 걸어보세요.",
    category: "걷기",
    difficulty: 1,
    similarityGroup: "ANSEONG_GEUMGWANG_WALK",
    status: "ACTIVE",
    kind: "WALK_DISTANCE",
    verificationPolicy: { type: "GPS_DISTANCE", minimumKilometers: 1 },
    targetValue: 1,
    targetUnit: "KILOMETER",
    placeTitle: "금광호수",
    address: "경기도 안성시 금광면 금광리 492-4",
    latitude: 36.9967389,
    longitude: 127.3310694,
  },
  {
    order: 9,
    title: "호수가 담은 순간",
    description: "하늘이나 주변 풍경이 호수에 비친 순간을 기록하세요.",
    category: "관찰·수집",
    difficulty: 1,
    similarityGroup: "ANSEONG_GEUMGWANG_PHOTO",
    status: "ACTIVE",
    kind: "COMPOSITE",
    verificationPolicy: { type: "COMPOSITE", photoVerificationMode: "AI", requiredSubject: "금광호수 수면에 비친 하늘 또는 주변 풍경", fallbackToAdminReview: true, requirements: [{ type: "GPS", count: 1, radiusM: 500 }, { type: "PHOTO", count: 1 }] },
    targetValue: null,
    targetUnit: null,
    placeTitle: "금광호수",
    address: "경기도 안성시 금광면 금광리 492-4",
    latitude: 36.9967389,
    longitude: 127.3310694,
  },
  {
    order: 10,
    title: "시를 밟는 걸음",
    description: "박두진 문학길을 걸으며 시와 자연이 함께하는 길을 느껴보세요.",
    category: "걷기",
    difficulty: 1,
    similarityGroup: "ANSEONG_POET_WALK",
    status: "ACTIVE",
    kind: "WALK_DISTANCE",
    verificationPolicy: { type: "GPS_DISTANCE", minimumKilometers: 1 },
    targetValue: 1,
    targetUnit: "KILOMETER",
    placeTitle: "박두진 문학길",
    address: "경기도 안성시 금광면 현곡리 43-6",
    latitude: 36.9859913,
    longitude: 127.343267,
  },
  {
    order: 11,
    title: "길 위의 한 문장",
    description: "박두진 문학길에서 마음에 머무는 시나 문장을 발견해보세요.",
    category: "탐색",
    difficulty: 1,
    similarityGroup: "ANSEONG_POET_WALK",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("AI", { requiredSubject: "박두진 문학길에 전시된 시 또는 문장" }),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: "박두진 문학길",
    address: "경기도 안성시 금광면 현곡리 43-6",
    latitude: 36.9859913,
    longitude: 127.343267,
  },
  {
    order: 12,
    title: "청록을 찾아서",
    description: "박두진의 시를 떠올리며 자연 속에서 '청록'을 닮은 색을 찾아보세요.",
    category: "관찰·수집",
    difficulty: 1,
    similarityGroup: "ANSEONG_POET_WALK",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("AI", { requiredColor: "청록색 또는 푸른 녹색" }),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: "박두진 문학길",
    address: "경기도 안성시 금광면 현곡리 43-6",
    latitude: 36.9859913,
    longitude: 127.343267,
  },
  {
    order: 13,
    title: "천년의 문을 열다",
    description: "오랜 시간을 간직한 칠장사에 도착해 천천히 둘러보세요.",
    category: "탐방",
    difficulty: 1,
    similarityGroup: "ANSEONG_CHILJANGSA",
    status: "ACTIVE",
    kind: "PLACE_VISIT",
    verificationPolicy: { maximumAccuracyM: 80, maximumAgeMs: 60000 },
    targetValue: null,
    targetUnit: null,
    placeTitle: "칠장사",
    address: "경기도 안성시 죽산면 칠장로 399-18",
    latitude: 37.026257,
    longitude: 127.3970664,
  },
  {
    order: 14,
    title: "기와에 머문 시간",
    description: "칠장사에서 세월이 느껴지는 전통건축의 한 장면을 담아보세요.",
    category: "관찰·수집",
    difficulty: 1,
    similarityGroup: "ANSEONG_CHILJANGSA",
    status: "ACTIVE",
    kind: "COMPOSITE",
    verificationPolicy: { type: "COMPOSITE", photoVerificationMode: "AI", requiredSubject: "칠장사의 전통 건축 또는 기와", fallbackToAdminReview: true, requirements: [{ type: "GPS", count: 1, radiusM: 250 }, { type: "PHOTO", count: 1 }] },
    targetValue: null,
    targetUnit: null,
    placeTitle: "칠장사",
    address: "경기도 안성시 죽산면 칠장로 399-18",
    latitude: 37.026257,
    longitude: 127.3970664,
  },
  {
    order: 15,
    title: "어사의 소원",
    description: "Quiz! 칠장사 나한전에서 기도한 뒤 과거에 급제했다고 전해지는 인물은 누구일까요?",
    category: "퀴즈",
    difficulty: 3,
    similarityGroup: "ANSEONG_CHILJANGSA",
    status: "ACTIVE",
    kind: "QUIZ",
    verificationPolicy: quizPolicy("박문수", undefined, "정답! 칠장사에는 박문수가 나한전에서 기도한 뒤 과거에 급제했다는 이야기가 전해져요."),
    targetValue: null,
    targetUnit: null,
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 16,
    title: "별빛이 흐르는 곳",
    description: "이름부터 아름다운 미리내성지를 찾아가보세요.",
    category: "탐방",
    difficulty: 1,
    similarityGroup: "ANSEONG_MIRINAE",
    status: "ACTIVE",
    kind: "PLACE_VISIT",
    verificationPolicy: { maximumAccuracyM: 80, maximumAgeMs: 60000 },
    targetValue: null,
    targetUnit: null,
    placeTitle: "미리내성지",
    address: "경기도 안성시 양성면 미리내성지로 420",
    latitude: 37.1451759,
    longitude: 127.2595948,
  },
  {
    order: 17,
    title: "밤하늘의 우리말",
    description: "Quiz! 순우리말 '미리내'는 무엇을 뜻할까요?",
    category: "퀴즈",
    difficulty: 2,
    similarityGroup: "ANSEONG_MIRINAE",
    status: "ACTIVE",
    kind: "QUIZ",
    verificationPolicy: quizPolicy("은하수", ["①별똥별", "②북극성", "③은하수", "④달무리"]),
    targetValue: null,
    targetUnit: null,
    placeTitle: "미리내성지",
    address: "경기도 안성시 양성면 미리내성지로 420",
    latitude: 37.1451759,
    longitude: 127.2595948,
  },
  {
    order: 18,
    title: "성곽 따라 한걸음",
    description: "죽주산성의 성곽길을 따라 걸으며 옛 성의 흔적을 만나보세요.",
    category: "걷기",
    difficulty: 2,
    similarityGroup: "ANSEONG_JUKJUSANSEONG",
    status: "ACTIVE",
    kind: "WALK_DISTANCE",
    verificationPolicy: { type: "GPS_DISTANCE", minimumKilometers: 1 },
    targetValue: 1,
    targetUnit: "KILOMETER",
    placeTitle: "죽주산성",
    address: "경기도 안성시 죽산면 매산리",
    latitude: 37.0900473,
    longitude: 127.4358653,
  },
  {
    order: 19,
    title: "그때 그 골목",
    description: "6070 추억의 거리에서 새로운 추억을 기록하세요.",
    category: "관찰·수집",
    difficulty: 1,
    similarityGroup: "ANSEONG_6070_STREET",
    status: "ACTIVE",
    kind: "COMPOSITE",
    verificationPolicy: { type: "COMPOSITE", photoVerificationMode: "RECORD", requirements: [{ type: "GPS", count: 1, radiusM: 250 }, { type: "PHOTO", count: 1 }] },
    targetValue: null,
    targetUnit: null,
    placeTitle: "6070 추억의 거리",
    address: "경기도 안성시 성남동 373",
    latitude: 37.0020115,
    longitude: 127.2706056,
  },
  {
    order: 20,
    title: "오래된 간판",
    description: "원도심에서 오래된 분위기가 느껴지는 간판 하나를 찾아보세요.",
    category: "관찰·수집",
    difficulty: 1,
    similarityGroup: "ANSEONG_6070_STREET",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("AI", { requiredSubject: "오래된 분위기의 상점 간판" }),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: "6070 추억의 거리",
    address: "경기도 안성시 성남동 373",
    latitude: 37.0020115,
    longitude: 127.2706056,
  },
  {
    order: 21,
    title: "장날의 풍경",
    description: "전통시장을 걸으며 활기차다고 느껴지는 장면을 찾아보세요.",
    category: "관찰·수집",
    difficulty: 1,
    similarityGroup: "ANSEONG_MARKET",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("RECORD", { caution: "안성 장날은 2일, 7일입니다." }),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 22,
    title: "시간이 머문 자리",
    description: "낙원역사공원을 찾아 안성 원도심의 시간을 느껴보세요.",
    category: "탐방",
    difficulty: 1,
    similarityGroup: "ANSEONG_NAKWON",
    status: "ACTIVE",
    kind: "PLACE_VISIT",
    verificationPolicy: { maximumAccuracyM: 80, maximumAgeMs: 60000 },
    targetValue: null,
    targetUnit: null,
    placeTitle: "낙원역사공원",
    address: "경기도 안성시 낙원동",
    latitude: 37.0050881,
    longitude: 127.2732545,
  },
  {
    order: 23,
    title: "초원 너머로",
    description: "넓은 들판과 하늘이 함께 펼쳐지는 장면을 사진으로 남겨보세요.",
    category: "관찰·수집",
    difficulty: 1,
    similarityGroup: "ANSEONG_FARMLAND",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("AI", { requiredSubject: "넓은 들판과 하늘이 함께 보이는 풍경" }),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: "안성팜랜드",
    address: "경기도 안성시 공도읍 대신두길 28",
    latitude: 36.9919657,
    longitude: 127.1934818,
  },
  {
    order: 24,
    title: "하늘 가까이",
    description: "금광호수 하늘전망대에 올라 탁 트인 금광호수의 풍경을 만나보세요.",
    category: "탐방",
    difficulty: 2,
    similarityGroup: "ANSEONG_SKY_OBSERVATORY",
    status: "ACTIVE",
    kind: "PLACE_VISIT",
    verificationPolicy: { maximumAccuracyM: 100, maximumAgeMs: 60000, caution: "운영시간과 기상 상황을 미리 확인해주세요." },
    targetValue: null,
    targetUnit: null,
    placeTitle: "금광호수 하늘전망대",
    address: "경기도 안성시 금광면 오흥리 산69-2",
    latitude: 36.9949991,
    longitude: 127.3332012,
  },
  {
    order: 25,
    title: "호수와 산 함께",
    description: "금광호수와 주변 산세가 함께 보이는 장면을 담아보세요.",
    category: "관찰·수집",
    difficulty: 2,
    similarityGroup: "ANSEONG_GEUMGWANG_PHOTO",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("AI", { requiredSubject: "금광호수와 주변 산세가 함께 보이는 풍경" }),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 26,
    title: "하늘 위 한 걸음",
    description: "숲 위로 이어지는 하늘 탐방로를 통해 금광호수 하늘전망대에 도달해보세요.",
    category: "탐방",
    difficulty: 2,
    similarityGroup: "ANSEONG_SKY_OBSERVATORY",
    status: "ACTIVE",
    kind: "PLACE_VISIT",
    verificationPolicy: { maximumAccuracyM: 100, maximumAgeMs: 60000, caution: "운영시간과 기상 상황을 미리 확인해주세요." },
    targetValue: null,
    targetUnit: null,
    placeTitle: "금광호수 하늘전망대",
    address: "경기도 안성시 금광면 오흥리 산69-2",
    latitude: 36.9949991,
    longitude: 127.3332012,
  },
  {
    order: 27,
    title: "호수 위 하늘전망대",
    description: "Quiz! 금광호수 하늘전망대의 높이는 얼마일까요?",
    category: "퀴즈",
    difficulty: 2,
    similarityGroup: "ANSEONG_SKY_OBSERVATORY",
    status: "ACTIVE",
    kind: "QUIZ",
    verificationPolicy: quizPolicy("21m", ["①19m", "②21m", "③23m", "④25m"], "정답! 금광호수 하늘전망대는 높이 21m로, 금광호수와 주변 산등성이를 한눈에 바라볼 수 있어요."),
    targetValue: null,
    targetUnit: null,
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 28,
    title: "그날의 함성을 따라",
    description: "안성 독립운동의 이야기가 남아 있는 안성3·1운동기념관을 찾아가보세요.",
    category: "탐방",
    difficulty: 1,
    similarityGroup: "ANSEONG_INDEPENDENCE",
    status: "ACTIVE",
    kind: "PLACE_VISIT",
    verificationPolicy: { maximumAccuracyM: 80, maximumAgeMs: 60000 },
    targetValue: null,
    targetUnit: null,
    placeTitle: "안성3·1운동기념관",
    address: "경기도 안성시 원곡면 만세로 868",
    latitude: 37.0628,
    longitude: 127.1779,
  },
  {
    order: 29,
    title: "1919, 그 날",
    description: "Quiz! 안성 양성·원곡의 대규모 만세항쟁이 일어난 날짜는 언제일까요?",
    category: "퀴즈",
    difficulty: 2,
    similarityGroup: "ANSEONG_INDEPENDENCE",
    status: "ACTIVE",
    kind: "QUIZ",
    verificationPolicy: quizPolicy("4월 1일", ["①3월 1일", "②3월 15일", "③4월 1일", "④4월 15일"], "정답! 안성 양성·원곡의 대규모 만세항쟁은 1919년 4월 1일에 일어났어요."),
    targetValue: null,
    targetUnit: null,
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 30,
    title: "해방의 시간",
    description: "Quiz! 안성 4·1만세항쟁 이후 일제 통치기관이 물러나며 만들어진 상황을 무엇이라고 할까요?",
    category: "퀴즈",
    difficulty: 3,
    similarityGroup: "ANSEONG_INDEPENDENCE",
    status: "ACTIVE",
    kind: "QUIZ",
    verificationPolicy: quizPolicy("2일간의 해방", undefined, "정답! 안성에서는 만세항쟁으로 일제의 통치기관을 몰아내며 '2일간의 해방'을 이뤄냈어요."),
    targetValue: null,
    targetUnit: null,
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 31,
    title: "바람 속 태극",
    description: "바람에 흩날리는 태극기를 멋지게 담아보세요.",
    category: "관찰·수집",
    difficulty: 1,
    similarityGroup: "ANSEONG_INDEPENDENCE",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("AI", { requiredSubject: "바람에 펄럭이는 태극기" }),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: "안성3·1운동기념관",
    address: "경기도 안성시 원곡면 만세로 868",
    latitude: 37.0628,
    longitude: 127.1779,
  },
  {
    order: 32,
    title: "독립의 한 줄",
    description: "전시를 둘러본 뒤 가장 기억에 남은 이야기를 한 문장으로 기록해보세요.",
    category: "기록",
    difficulty: 1,
    similarityGroup: "ANSEONG_INDEPENDENCE",
    status: "ACTIVE",
    kind: "CHECK_IN",
    verificationPolicy: { type: "TEXT", maxLength: 140 },
    targetValue: null,
    targetUnit: null,
    placeTitle: "안성3·1운동기념관",
    address: "경기도 안성시 원곡면 만세로 868",
    latitude: 37.0628,
    longitude: 127.1779,
  },
  {
    order: 33,
    title: "들판에 핀 계절",
    description: "지금 계절을 가장 잘 보여주는 팜랜드의 풍경을 한 장 남겨보세요.",
    category: "관찰·수집",
    difficulty: 1,
    similarityGroup: "ANSEONG_FARMLAND",
    status: "ACTIVE",
    kind: "COMPOSITE",
    verificationPolicy: { type: "COMPOSITE", photoVerificationMode: "RECORD", requirements: [{ type: "GPS", count: 1, radiusM: 500 }, { type: "PHOTO", count: 1 }] },
    targetValue: null,
    targetUnit: null,
    placeTitle: "안성팜랜드",
    address: "경기도 안성시 공도읍 대신두길 28",
    latitude: 36.9919657,
    longitude: 127.1934818,
  },
  {
    order: 34,
    title: "동물 친구",
    description: "팜랜드에서 동물 친구를 만나 사진을 찍어보세요.",
    category: "관찰·수집",
    difficulty: 1,
    similarityGroup: "ANSEONG_FARMLAND",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("AI", { requiredSubject: "안성팜랜드에서 만난 동물" }),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: "안성팜랜드",
    address: "경기도 안성시 공도읍 대신두길 28",
    latitude: 36.9919657,
    longitude: 127.1934818,
  },
  {
    order: 35,
    title: "안성맞춤랜드를 한눈에",
    description: "높은 곳에 올라 안성맞춤랜드의 풍경을 담아보세요.",
    category: "탐방",
    difficulty: 1,
    similarityGroup: "ANSEONG_MATCHUMLAND",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("RECORD"),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: "안성맞춤랜드",
    address: "경기도 안성시 보개면 남사당로 198",
    latitude: 37.032398,
    longitude: 127.3107528,
  },
  {
    order: 36,
    title: "OO모양 수변공원",
    description: "Quiz! 안성맞춤랜드 수변공원은 남사당놀이의 어떤 물건을 형상화했을까요?",
    category: "퀴즈",
    difficulty: 3,
    similarityGroup: "ANSEONG_MATCHUMLAND",
    status: "ACTIVE",
    kind: "QUIZ",
    verificationPolicy: quizPolicy("상모", undefined, "정답! 안성맞춤랜드 수변공원은 남사당놀이의 상모를 형상화해 조성된 공간이에요."),
    targetValue: null,
    targetUnit: null,
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 37,
    title: "잔디 위 쉼표",
    description: "잔디광장 주변에서 5분 동안 잠시 쉬어가요.",
    category: "체류",
    difficulty: 1,
    similarityGroup: "ANSEONG_MATCHUMLAND",
    status: "ACTIVE",
    kind: "COMPOSITE",
    verificationPolicy: { type: "GPS_STAY", durationSeconds: 300, minimumSeconds: 300, allowedDriftM: 100 },
    targetValue: 300,
    targetUnit: "SECOND",
    placeTitle: "안성맞춤랜드",
    address: "경기도 안성시 보개면 남사당로 198",
    latitude: 37.032398,
    longitude: 127.3107528,
  },
  {
    order: 38,
    title: "기억의 빛",
    description: "어둠이 내려앉은 칠곡호수에서 음악과 빛, 물이 어우러지는 순간을 만나보세요.",
    category: "관찰·수집",
    difficulty: 2,
    similarityGroup: "ANSEONG_CHILGOK_LAKE",
    status: "ACTIVE",
    kind: "COMPOSITE",
    verificationPolicy: { type: "COMPOSITE", photoVerificationMode: "AI", requiredSubject: "칠곡호수의 음악분수 또는 야간 빛 풍경", fallbackToAdminReview: true, caution: "사전에 운영일과 기상 상황을 확인해주세요.", requirements: [{ type: "GPS", count: 1, radiusM: 400 }, { type: "PHOTO", count: 1 }] },
    targetValue: null,
    targetUnit: null,
    placeTitle: "칠곡호수공원",
    address: "경기도 안성시 원곡면 칠곡리 842",
    latitude: 37.0487498,
    longitude: 127.1556876,
  },
  {
    order: 39,
    title: "127개의 기억",
    description: "Quiz! 음악분수의 127개 물줄기가 기억하는 숫자 127은 무엇을 의미할까요?",
    category: "퀴즈",
    difficulty: 2,
    similarityGroup: "ANSEONG_CHILGOK_LAKE",
    status: "ACTIVE",
    kind: "QUIZ",
    verificationPolicy: quizPolicy("실형을 선고받은 안성 만세운동 참가자 127명", ["①실형을 선고받은 안성 만세운동 참가자 127명", "②안성의 127개 마을", "③음악분수 제작에 참여한 127명", "④만세운동이 이어진 127일"]),
    targetValue: null,
    targetUnit: null,
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 40,
    title: "안성 여행 한 줄 소감",
    description: "안성 여행을 대표하는 사진 한 장과 한 줄 소감을 기록해보세요.",
    category: "기록",
    difficulty: 1,
    similarityGroup: "ANSEONG_TRAVEL_NOTE",
    status: "ACTIVE",
    kind: "COMPOSITE",
    verificationPolicy: { type: "COMPOSITE", photoVerificationMode: "RECORD", requirements: [{ type: "PHOTO", count: 1 }, { type: "TEXT", count: 1, maxLength: 140 }] },
    targetValue: null,
    targetUnit: null,
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 41,
    title: "안성맞춤 글자 찾기",
    description: "여행하면서 '안성' 또는 '안성맞춤' 글자를 찾아보세요.",
    category: "관찰·수집",
    difficulty: 2,
    similarityGroup: "ANSEONG_SIGN",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("AI", { requiredText: "안성 또는 안성맞춤" }),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
] as const;
