const photoPolicy = (
  mode: "AI" | "RECORD",
  extra: Record<string, unknown> = {},
) => ({
  type: "PHOTO",
  requiredPhotoCount: 1,
  photoVerificationMode: mode,
  ...(mode === "AI" ? { fallbackToAdminReview: true } : {}),
  ...extra,
});

const quizPolicy = (
  answer: string,
  choices?: readonly string[],
  explanation?: string,
) => ({
  type: "QUIZ",
  answer,
  ...(choices ? { choices: [...choices] } : {}),
  ...(explanation ? { explanation } : {}),
});

const visitPolicy = (caution?: string) => ({
  type: "GPS",
  maximumAccuracyM: 100,
  maximumAgeMs: 60000,
  ...(caution ? { caution } : {}),
});

const gpsPhotoPolicy = (caution?: string) => ({
  type: "COMPOSITE",
  requirements: [
    { type: "GPS", count: 1 },
    { type: "PHOTO", count: 1 },
  ],
  photoVerificationMode: "RECORD",
  ...(caution ? { caution } : {}),
});

export const buyeoMissionSeed = [
  {
    order: 1,
    title: "사비, 첫걸음",
    description: "옛 백제의 수도였던 부여에서 1km를 산책해봐요.",
    category: "걷기",
    difficulty: 1,
    similarityGroup: "BUYEO_WALK",
    status: "ACTIVE",
    kind: "WALK_DISTANCE",
    verificationPolicy: { type: "GPS_DISTANCE", minimumAccuracyM: 100 },
    targetValue: 1000,
    targetUnit: "METER",
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 2,
    title: "오늘의 부여 한 장",
    description: "나만의 부여 포토 스팟을 찾아 한 장으로 기록해보세요.",
    category: "기록",
    difficulty: 1,
    similarityGroup: "BUYEO_FREE_RECORD",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("RECORD"),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 3,
    title: "백제를 찾아서",
    description: "'백제'라는 글자가 적힌 곳을 발견해보세요.",
    category: "관찰",
    difficulty: 1,
    similarityGroup: "BUYEO_BAEKJE_TEXT",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("AI", { requiredText: "백제" }),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 4,
    title: "사비의 흔적",
    description: "부여를 걸으며 백제와 관련된 유적이나 상징 하나를 찾아보세요.",
    category: "관찰",
    difficulty: 1,
    similarityGroup: "BUYEO_BAEKJE_TRACE",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("AI", { requiredSubject: "백제와 관련된 유적 또는 상징" }),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 5,
    title: "시간이 머문 자리",
    description: "세월의 흔적이 느껴지는 부여의 한 장면을 찾아보세요.",
    category: "관찰",
    difficulty: 1,
    similarityGroup: "BUYEO_OLD_SCENE",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("AI", { requiredSubject: "세월의 흔적이 느껴지는 오래된 건축물이나 거리 풍경" }),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 6,
    title: "연꽃의 고장",
    description: "부여에서 연꽃 또는 연꽃을 활용한 문양·상품·조형물을 찾아보세요.",
    category: "관찰",
    difficulty: 1,
    similarityGroup: "BUYEO_LOTUS",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("AI", { requiredSubject: "연꽃 또는 연꽃 문양·상품·조형물" }),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 7,
    title: "백제의 수도는?",
    description: "Quiz! 백제가 마지막으로 수도를 옮긴 곳은 어디일까요?",
    category: "퀴즈",
    difficulty: 2,
    similarityGroup: "BUYEO_HISTORY_QUIZ",
    status: "ACTIVE",
    kind: "QUIZ",
    verificationPolicy: quizPolicy("사비", ["①한성", "②사비", "③웅진", "④금성"], "정답! 백제는 538년 수도를 웅진에서 사비로 옮겼어요."),
    targetValue: null,
    targetUnit: null,
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 8,
    title: "왕궁의 남쪽 연못",
    description: "백제 왕궁 남쪽에 만들어졌다고 전해지는 궁남지를 찾아가보세요.",
    category: "탐방",
    difficulty: 1,
    similarityGroup: "BUYEO_GUNGNAMJI",
    status: "ACTIVE",
    kind: "PLACE_VISIT",
    verificationPolicy: visitPolicy(),
    targetValue: null,
    targetUnit: null,
    placeTitle: "궁남지",
    address: "충청남도 부여군 부여읍 궁남로 52",
    latitude: 36.2696855,
    longitude: 126.9122051,
  },
  {
    order: 9,
    title: "연못 위 한 장",
    description: "궁남지에서 물과 주변 풍경이 어우러지는 순간을 담아보세요.",
    category: "관찰",
    difficulty: 1,
    similarityGroup: "BUYEO_GUNGNAMJI_PHOTO",
    status: "ACTIVE",
    kind: "COMPOSITE",
    verificationPolicy: gpsPhotoPolicy(),
    targetValue: null,
    targetUnit: null,
    placeTitle: "궁남지",
    address: "충청남도 부여군 부여읍 궁남로 52",
    latitude: 36.2696855,
    longitude: 126.9122051,
  },
  {
    order: 10,
    title: "물 위의 정자",
    description: "궁남지의 포룡정과 연못이 함께 보이는 나만의 구도를 찾아보세요.",
    category: "관찰",
    difficulty: 1,
    similarityGroup: "BUYEO_GUNGNAMJI_PHOTO",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("AI", { requiredSubject: "궁남지 포룡정과 연못이 함께 보이는 풍경" }),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: "궁남지",
    address: "충청남도 부여군 부여읍 궁남로 52",
    latitude: 36.2696855,
    longitude: 126.9122051,
  },
  {
    order: 11,
    title: "연꽃 사이로",
    description: "궁남지에서 연꽃 또는 연잎이 만들어내는 풍경을 찾아보세요.",
    category: "관찰",
    difficulty: 1,
    similarityGroup: "BUYEO_GUNGNAMJI_PHOTO",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("AI", { requiredSubject: "궁남지의 연꽃 또는 연잎 풍경" }),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: "궁남지",
    address: "충청남도 부여군 부여읍 궁남로 52",
    latitude: 36.2696855,
    longitude: 126.9122051,
  },
  {
    order: 12,
    title: "634년의 연못",
    description: "Quiz! 『삼국사기』에 궁남지 조성과 관련된 기록이 등장하는 백제 왕은 누구일까요?",
    category: "퀴즈",
    difficulty: 3,
    similarityGroup: "BUYEO_GUNGNAMJI_QUIZ",
    status: "ACTIVE",
    kind: "QUIZ",
    verificationPolicy: quizPolicy("무왕", undefined, "정답! 『삼국사기』에는 무왕 35년인 634년에 궁남지를 조성한 기록이 전해져요."),
    targetValue: null,
    targetUnit: null,
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 13,
    title: "서동의 사랑노래",
    description: "Quiz! 궁남지와 함께 전해지는 서동의 사랑 이야기 속 신라 공주는 누구일까요?",
    category: "퀴즈",
    difficulty: 3,
    similarityGroup: "BUYEO_GUNGNAMJI_QUIZ",
    status: "ACTIVE",
    kind: "QUIZ",
    verificationPolicy: quizPolicy("선화공주", undefined, "정답! 서동요 설화에는 서동과 신라 선화공주의 사랑 이야기가 전해져요."),
    targetValue: null,
    targetUnit: null,
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 14,
    title: "다섯 층의 시간",
    description: "백제의 석탑이 남아 있는 정림사지를 찾아가보세요.",
    category: "탐방",
    difficulty: 1,
    similarityGroup: "BUYEO_JEONGNIMSAJI",
    status: "ACTIVE",
    kind: "PLACE_VISIT",
    verificationPolicy: visitPolicy(),
    targetValue: null,
    targetUnit: null,
    placeTitle: "정림사지",
    address: "충청남도 부여군 부여읍 동남리 254",
    latitude: 36.2792635,
    longitude: 126.9144085,
  },
  {
    order: 15,
    title: "백제의 선을 담다",
    description: "정림사지 오층석탑의 균형과 형태가 잘 보이는 한 장을 남겨보세요.",
    category: "기록",
    difficulty: 1,
    similarityGroup: "BUYEO_JEONGNIMSAJI_PHOTO",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("RECORD"),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: "정림사지",
    address: "충청남도 부여군 부여읍 동남리 254",
    latitude: 36.2792635,
    longitude: 126.9144085,
  },
  {
    order: 16,
    title: "절터에서의 쉼",
    description: "옛 정림사가 있었던 터를 천천히 둘러보며 10분간 머물러 보세요.",
    category: "체류",
    difficulty: 1,
    similarityGroup: "BUYEO_JEONGNIMSAJI_STAY",
    status: "ACTIVE",
    kind: "COMPOSITE",
    verificationPolicy: { type: "GPS_STAY", durationSeconds: 600, maximumAccuracyM: 100, maximumAgeMs: 60000 },
    targetValue: 600,
    targetUnit: "SECOND",
    placeTitle: "정림사지",
    address: "충청남도 부여군 부여읍 동남리 254",
    latitude: 36.2792635,
    longitude: 126.9144085,
  },
  {
    order: 17,
    title: "탑과 하늘 사이",
    description: "오층석탑과 오늘의 하늘이 함께 보이는 장면을 담아보세요.",
    category: "기록",
    difficulty: 1,
    similarityGroup: "BUYEO_JEONGNIMSAJI_PHOTO",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("RECORD"),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: "정림사지",
    address: "충청남도 부여군 부여읍 동남리 254",
    latitude: 36.2792635,
    longitude: 126.9144085,
  },
  {
    order: 18,
    title: "왕도를 지키던 산",
    description: "백제 왕궁의 배후를 지키던 부소산을 찾아가보세요.",
    category: "탐방",
    difficulty: 1,
    similarityGroup: "BUYEO_BUSOSAN",
    status: "ACTIVE",
    kind: "PLACE_VISIT",
    verificationPolicy: visitPolicy("경사가 있는 산길이므로 편한 신발을 착용해주세요."),
    targetValue: null,
    targetUnit: null,
    placeTitle: "부소산",
    address: "충청남도 부여군 부여읍 부소로 31",
    latitude: 36.2886,
    longitude: 126.9182528,
  },
  {
    order: 19,
    title: "숲에 남은 백제",
    description: "부소산 숲길을 따라 1km 이상 걸어보세요.",
    category: "걷기",
    difficulty: 2,
    similarityGroup: "BUYEO_BUSOSAN_WALK",
    status: "ACTIVE",
    kind: "WALK_DISTANCE",
    verificationPolicy: { type: "GPS_DISTANCE", minimumAccuracyM: 100, caution: "경사가 있는 산길이므로 편한 신발을 착용해주세요." },
    targetValue: 1000,
    targetUnit: "METER",
    placeTitle: "부소산",
    address: "충청남도 부여군 부여읍 부소로 31",
    latitude: 36.2886,
    longitude: 126.9182528,
  },
  {
    order: 20,
    title: "꽃이 된 이야기",
    description: "낙화암에 도착해 백마강이 내려다보이는 풍경을 만나보세요.",
    category: "탐방",
    difficulty: 2,
    similarityGroup: "BUYEO_BUSOSAN",
    status: "ACTIVE",
    kind: "PLACE_VISIT",
    verificationPolicy: visitPolicy("절벽과 급경사 구간에서 안전에 주의해주세요."),
    targetValue: null,
    targetUnit: null,
    placeTitle: "낙화암",
    address: "충청남도 부여군 부여읍 부소로 31",
    latitude: 36.2924042,
    longitude: 126.9121858,
  },
  {
    order: 21,
    title: "절벽 위의 정자",
    description: "낙화암 위 백화정을 찾아가보세요.",
    category: "탐방",
    difficulty: 2,
    similarityGroup: "BUYEO_BUSOSAN",
    status: "ACTIVE",
    kind: "PLACE_VISIT",
    verificationPolicy: visitPolicy("절벽과 급경사 구간에서 안전에 주의해주세요."),
    targetValue: null,
    targetUnit: null,
    placeTitle: "백화정",
    address: "충청남도 부여군 부여읍 부소로 31",
    latitude: 36.2921766,
    longitude: 126.9119243,
  },
  {
    order: 22,
    title: "고란초를 찾아서",
    description: "고란사와 관련된 이름의 주인공 '고란초'를 찾아보세요.",
    category: "관찰",
    difficulty: 3,
    similarityGroup: "BUYEO_GORANSA",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("AI", { requiredSubject: "고란초 식물 또는 고란초 안내판" }),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: "고란사",
    address: "충청남도 부여군 부여읍 부소로 1-25",
    latitude: 36.2926145,
    longitude: 126.9131602,
  },
  {
    order: 23,
    title: "백제의 세 충신",
    description: "Quiz! 부소산 삼충사에 모셔진 백제 충신은 성충·흥수·OO입니다. OO은 누구일까요?",
    category: "퀴즈",
    difficulty: 2,
    similarityGroup: "BUYEO_HISTORY_QUIZ",
    status: "ACTIVE",
    kind: "QUIZ",
    verificationPolicy: quizPolicy("계백", ["①윤충", "②흑치상지", "③복신", "④계백"], "정답! 삼충사에는 성충·흥수·계백의 위패가 모셔져 있어요."),
    targetValue: null,
    targetUnit: null,
    placeTitle: null,
    address: null,
    latitude: null,
    longitude: null,
  },
  {
    order: 24,
    title: "곡식을 지키던 곳",
    description: "백제시대 곡식을 저장했던 것으로 알려진 군창지를 찾아보세요.",
    category: "탐방",
    difficulty: 2,
    similarityGroup: "BUYEO_BUSOSAN",
    status: "ACTIVE",
    kind: "PLACE_VISIT",
    verificationPolicy: visitPolicy(),
    targetValue: null,
    targetUnit: null,
    placeTitle: "군창지",
    address: "충청남도 부여군 부여읍 부소로 31",
    latitude: 36.2886392,
    longitude: 126.9179996,
  },
  {
    order: 25,
    title: "산성 한 바퀴",
    description: "부소산성 안의 지정 탐방로를 따라 1km 이상 걸어보세요.",
    category: "걷기",
    difficulty: 2,
    similarityGroup: "BUYEO_BUSOSAN_WALK",
    status: "ACTIVE",
    kind: "WALK_DISTANCE",
    verificationPolicy: { type: "GPS_DISTANCE", minimumAccuracyM: 100, caution: "지정 탐방로를 이용하고 경사 구간에서 안전에 주의해주세요." },
    targetValue: 1000,
    targetUnit: "METER",
    placeTitle: "부소산성",
    address: "충청남도 부여군 부여읍 부소로 31",
    latitude: 36.2892424,
    longitude: 126.9151865,
  },
  {
    order: 26,
    title: "백마강 한 장",
    description: "백마강에서 오늘 가장 마음에 드는 강 풍경을 남겨보세요.",
    category: "기록",
    difficulty: 1,
    similarityGroup: "BUYEO_GUDRAE",
    status: "ACTIVE",
    kind: "COMPOSITE",
    verificationPolicy: gpsPhotoPolicy("물가 가까이에서는 안전에 주의해주세요."),
    targetValue: null,
    targetUnit: null,
    placeTitle: "백마강 구드래 일원",
    address: "충청남도 부여군 부여읍 백강로 148",
    latitude: 36.276455,
    longitude: 126.8994326,
  },
  {
    order: 27,
    title: "구드래의 오후",
    description: "구드래 일원을 천천히 걸으며 마음에 드는 풍경을 찾아보세요.",
    category: "탐방",
    difficulty: 1,
    similarityGroup: "BUYEO_GUDRAE",
    status: "ACTIVE",
    kind: "COMPOSITE",
    verificationPolicy: gpsPhotoPolicy(),
    targetValue: null,
    targetUnit: null,
    placeTitle: "구드래 일원",
    address: "충청남도 부여군 부여읍 백강로 148",
    latitude: 36.276455,
    longitude: 126.8994326,
  },
  {
    order: 28,
    title: "작품 사이로",
    description: "구드래조각공원에서 가장 마음에 드는 작품 하나를 골라 사진으로 남겨보세요.",
    category: "관찰",
    difficulty: 1,
    similarityGroup: "BUYEO_GUDRAE",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("RECORD"),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: "구드래조각공원",
    address: "충청남도 부여군 부여읍 백강로 148",
    latitude: 36.276455,
    longitude: 126.8994326,
  },
  {
    order: 29,
    title: "왕들이 잠든 자리",
    description: "백제 왕실의 무덤이 모여 있는 부여 왕릉원을 찾아가보세요.",
    category: "탐방",
    difficulty: 1,
    similarityGroup: "BUYEO_ROYAL_TOMBS",
    status: "ACTIVE",
    kind: "PLACE_VISIT",
    verificationPolicy: visitPolicy(),
    targetValue: null,
    targetUnit: null,
    placeTitle: "부여 왕릉원",
    address: "충청남도 부여군 부여읍 왕릉로 61",
    latitude: 36.2772086,
    longitude: 126.9428667,
  },
  {
    order: 30,
    title: "봉분 사이로",
    description: "왕릉원의 고분과 자연이 함께 보이는 풍경을 담아보세요.",
    category: "관찰",
    difficulty: 1,
    similarityGroup: "BUYEO_ROYAL_TOMBS",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("RECORD"),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: "부여 왕릉원",
    address: "충청남도 부여군 부여읍 왕릉로 61",
    latitude: 36.2772086,
    longitude: 126.9428667,
  },
  {
    order: 31,
    title: "향로 속 세상",
    description: "금동대향로에서 가장 인상 깊은 동물·인물·무늬를 찾아보세요.",
    category: "관찰",
    difficulty: 1,
    similarityGroup: "BUYEO_MUSEUM",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("AI", { requiredSubject: "백제금동대향로 또는 전시된 금동대향로의 동물·인물·무늬" }),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: "국립부여박물관",
    address: "충청남도 부여군 부여읍 금성로 5",
    latitude: 36.2763114,
    longitude: 126.919051,
  },
  {
    order: 32,
    title: "왕궁을 걷다",
    description: "백제문화단지의 사비궁을 찾아 왕궁 공간을 둘러보세요.",
    category: "탐방",
    difficulty: 1,
    similarityGroup: "BUYEO_CULTURAL_LAND",
    status: "ACTIVE",
    kind: "PLACE_VISIT",
    verificationPolicy: visitPolicy("운영시간과 휴관일을 미리 확인해주세요."),
    targetValue: null,
    targetUnit: null,
    placeTitle: "백제문화단지 사비궁",
    address: "충청남도 부여군 규암면 백제문로 455",
    latitude: 36.307382,
    longitude: 126.907241,
  },
  {
    order: 33,
    title: "궁궐 한 컷",
    description: "사비궁에서 백제 왕궁의 분위기가 가장 잘 느껴지는 장면을 담아보세요.",
    category: "관찰",
    difficulty: 1,
    similarityGroup: "BUYEO_CULTURAL_LAND",
    status: "ACTIVE",
    kind: "PHOTO",
    verificationPolicy: photoPolicy("RECORD"),
    targetValue: 1,
    targetUnit: "PHOTO",
    placeTitle: "백제문화단지 사비궁",
    address: "충청남도 부여군 규암면 백제문로 455",
    latitude: 36.307382,
    longitude: 126.907241,
  },
  {
    order: 34,
    title: "다시 세운 능사",
    description: "능산리 유적을 실물 크기로 재현한 능사를 찾아가보세요.",
    category: "탐방",
    difficulty: 2,
    similarityGroup: "BUYEO_CULTURAL_LAND",
    status: "ACTIVE",
    kind: "PLACE_VISIT",
    verificationPolicy: visitPolicy("운영시간과 휴관일을 미리 확인해주세요."),
    targetValue: null,
    targetUnit: null,
    placeTitle: "백제문화단지 능사",
    address: "충청남도 부여군 규암면 백제문로 455",
    latitude: 36.307382,
    longitude: 126.907241,
  },
  {
    order: 35,
    title: "백제를 내려다보다",
    description: "제형루에 올라 백제문화단지가 펼쳐지는 풍경을 사진으로 남겨보세요.",
    category: "탐방",
    difficulty: 2,
    similarityGroup: "BUYEO_CULTURAL_LAND",
    status: "ACTIVE",
    kind: "COMPOSITE",
    verificationPolicy: gpsPhotoPolicy("운영시간과 휴관일을 미리 확인해주세요."),
    targetValue: null,
    targetUnit: null,
    placeTitle: "백제문화단지 제형루",
    address: "충청남도 부여군 규암면 백제문로 455",
    latitude: 36.307382,
    longitude: 126.907241,
  },
] as const;
